repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: bash
        args: [-c, 'UV_CACHE_DIR=.uv-cache uv run pytest tests']
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
