repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
