repos:
  - repo: local
    hooks:
      - id: black
        name: Black (uv)
        entry: uv
        args:
          - run
          - --no-sync
          - black
          - --config
          - pyproject.toml
        language: system
        types: [python]

      - id: ruff
        name: Ruff (uv)
        entry: uv
        args:
          - run
          - --no-sync
          - ruff
          - check
          - --fix
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests with coverage gate
        entry: bash
        args:
          - -c
          - >-
            UV_CACHE_DIR=.uv-cache uv run coverage run -m pytest tests &&
            UV_CACHE_DIR=.uv-cache uv run coverage report --fail-under=95
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
