"""Use either ISBN

Revision ID: 08b9aae217e6
Revises: c9180e554a91
Create Date: 2025-06-26 13:18:14.891365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b9aae217e6'
down_revision: Union[str, Sequence[str], None] = 'c9180e554a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(length=13), nullable=True))
    op.drop_constraint(op.f('books_isbn10_key'), 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.drop_column('books', 'isbn10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn10', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint(op.f('books_isbn10_key'), 'books', ['isbn10'], postgresql_nulls_not_distinct=False)
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
