"""Cascade

Revision ID: 31f543f7cb41
Revises: 63567a7b40e6
Create Date: 2025-07-05 18:50:25.938933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f543f7cb41'
down_revision: Union[str, Sequence[str], None] = '63567a7b40e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('elections_winner_fkey'), 'elections', type_='foreignkey')
    op.create_foreign_key(None, 'elections', 'books', ['winner'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('nominations_book_id_fkey'), 'nominations', type_='foreignkey')
    op.create_foreign_key(None, 'nominations', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('votes_book_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_election_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_election_id_fkey'), 'votes', 'elections', ['election_id'], ['id'])
    op.create_foreign_key(op.f('votes_book_id_fkey'), 'votes', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'nominations', type_='foreignkey')
    op.create_foreign_key(op.f('nominations_book_id_fkey'), 'nominations', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.create_foreign_key(op.f('elections_winner_fkey'), 'elections', 'books', ['winner'], ['id'])
    # ### end Alembic commands ###
