"""initial schema

Revision ID: 460392e8201a
Revises: 
Create Date: 2025-06-26 03:02:01.422876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460392e8201a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=12), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary_short', sa.Text(), nullable=False),
    sa.Column('summary_long', sa.Text(), nullable=False),
    sa.Column('price_paperback', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('price_kindle', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_audible', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin')
    )
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opener_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closes_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ballot', sa.JSON(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictor_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reminded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('nominator_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('reacted_users', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('voter_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('election_id', 'voter_discord_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('nominations')
    op.drop_table('predictions')
    op.drop_table('elections')
    op.drop_table('books')
    # ### end Alembic commands ###
