"""Remove message_id from Election

Revision ID: 63567a7b40e6
Revises: c6e5ca4cfaef
Create Date: 2025-07-05 17:15:30.606154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63567a7b40e6'
down_revision: Union[str, Sequence[str], None] = 'c6e5ca4cfaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
