"""remove book prices for now

Revision ID: 72b5854dbbb9
Revises: 460392e8201a
Create Date: 2025-06-26 03:59:55.953033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b5854dbbb9'
down_revision: Union[str, Sequence[str], None] = '460392e8201a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'price_audible')
    op.drop_column('books', 'price_paperback')
    op.drop_column('books', 'price_kindle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price_kindle', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('price_paperback', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('price_audible', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
