"""Allow for fractional voting

Revision ID: 78781a5c30bd
Revises: 0e5086ea61ee
Create Date: 2025-07-09 17:42:14.331386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78781a5c30bd'
down_revision: Union[str, Sequence[str], None] = '0e5086ea61ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nominations', sa.Column('reactions', sa.Integer(), nullable=True, server_default='0'))
    op.execute("UPDATE nominations SET reactions = 0 WHERE reactions IS NULL")
    op.alter_column('nominations', 'reactions', nullable=False)
    op.drop_column('nominations', 'reacted_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nominations', sa.Column('reacted_users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('nominations', 'reactions')
    # ### end Alembic commands ###
