"""Add winner field to elections

Revision ID: c6e5ca4cfaef
Revises: 25a3266455c7
Create Date: 2025-07-05 15:55:50.903512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e5ca4cfaef'
down_revision: Union[str, Sequence[str], None] = '25a3266455c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('winner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elections', 'books', ['winner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.drop_column('elections', 'winner')
    # ### end Alembic commands ###
