"""Use ISBN10 only

Revision ID: c9180e554a91
Revises: f21802b4bbf0
Create Date: 2025-06-26 04:41:41.066881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9180e554a91'
down_revision: Union[str, Sequence[str], None] = 'f21802b4bbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_isbn13_key'), 'books', type_='unique')
    op.drop_column('books', 'isbn13')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn13', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('books_isbn13_key'), 'books', ['isbn13'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
