"""Decouple from Amazon

Revision ID: f21802b4bbf0
Revises: 72b5854dbbb9
Create Date: 2025-06-26 04:38:35.555421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21802b4bbf0'
down_revision: Union[str, Sequence[str], None] = '72b5854dbbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('isbn10', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.String(length=13), nullable=True))
    op.add_column('books', sa.Column('length', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('books_asin_key'), 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['isbn13'])
    op.create_unique_constraint(None, 'books', ['isbn10'])
    op.drop_column('books', 'summary_short')
    op.drop_column('books', 'author')
    op.drop_column('books', 'asin')
    op.drop_column('books', 'summary_long')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('summary_long', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('asin', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('summary_short', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint(op.f('books_asin_key'), 'books', ['asin'], postgresql_nulls_not_distinct=False)
    op.drop_column('books', 'length')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn10')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
